package schoolModel

import "fmt"

/*
add all school of sysu
*/
func initSchool() {
	res := AddSchool(School{Name: "中国语言文学系", Type: "文科"})
	fmt.Println(res)
	AddSchool(School{Name: "历史学系", Type: "文科"})
	AddSchool(School{Name: "社会学与人类学学院", Type: "文科"})
	AddSchool(School{Name: "博雅学院", Type: "文科"})
	AddSchool(School{Name: "岭南学院", Type: "经管"})
	AddSchool(School{Name: "外国语学院", Type: "文科"})
	AddSchool(School{Name: "法学院", Type: "文科"})
	AddSchool(School{Name: "政治与公共事物管理学院", Type: "文科"})
	AddSchool(School{Name: "管理学院", Type: "经管"})
	AddSchool(School{Name: "马克思主义学院", Type: "文科"})
	AddSchool(School{Name: "心理学系", Type: "理工"})
	AddSchool(School{Name: "传播与设计学院", Type: "文科"})
	AddSchool(School{Name: "资讯管理学院", Type: "经管"})
	AddSchool(School{Name: "艺术学院", Type: "文科"})
	AddSchool(School{Name: "数学学院", Type: "理工"})
	AddSchool(School{Name: "物理学院", Type: "理工"})
	AddSchool(School{Name: "化学学院", Type: "理工"})
	AddSchool(School{Name: "地理科学与规划学院", Type: "理工"})
	AddSchool(School{Name: "生命科学学院", Type: "理工"})
	AddSchool(School{Name: "工学院", Type: "理工"})
	AddSchool(School{Name: "材料科学与工程学院", Type: "理工"})
	AddSchool(School{Name: "电子与信息工程学院", Type: "理工"})
	AddSchool(School{Name: "数据科学与计算机学院", Type: "理工"})
	AddSchool(School{Name: "环境科学与工程学院", Type: "理工"})
	AddSchool(School{Name: "中山医学院", Type: "医学"})
	AddSchool(School{Name: "光华口腔医学院", Type: "医学"})
	AddSchool(School{Name: "公共卫生学院", Type: "医学"})
	AddSchool(School{Name: "药学院", Type: "医学"})
	AddSchool(School{Name: "护理学院", Type: "医学"})
	AddSchool(School{Name: "中国语言文学系（珠海）", Type: "文科"})
	AddSchool(School{Name: "历史学系（珠海）", Type: "文科"})
	AddSchool(School{Name: "哲学系（珠海）", Type: "文科"})
	AddSchool(School{Name: "国际金融学院", Type: "经管"})
	AddSchool(School{Name: "国际翻译学院", Type: "文科"})
	AddSchool(School{Name: "国际关系学院", Type: "文科"})
	AddSchool(School{Name: "旅游学院", Type: "经管"})
	AddSchool(School{Name: "数学学院（珠海）", Type: "理工"})
	AddSchool(School{Name: "物理与天文学院", Type: "理工"})
	AddSchool(School{Name: "大气科学学院", Type: "理工"})
	AddSchool(School{Name: "海洋科学学院", Type: "理工"})
	AddSchool(School{Name: "地理科学与工程学院", Type: "理工"})
	AddSchool(School{Name: "化学工程与技术学院", Type: "理工"})
	AddSchool(School{Name: "海洋工程与技术学院", Type: "理工"})
	AddSchool(School{Name: "中法核工程与技术学院", Type: "理工"})
	AddSchool(School{Name: "土木工程学院", Type: "理工"})
	AddSchool(School{Name: "医学院", Type: "医学"})
	AddSchool(School{Name: "公共卫生学院（深圳）", Type: "医学"})
	AddSchool(School{Name: "药学院（深圳）", Type: "医学"})
	AddSchool(School{Name: "材料学院", Type: "理工"})
	AddSchool(School{Name: "生物医学工程学院", Type: "理工"})
	AddSchool(School{Name: "电子与通信工程学院", Type: "理工"})
	AddSchool(School{Name: "智能工程学院", Type: "理工"})
	AddSchool(School{Name: "航空航天学院", Type: "理工"})
}
